
## IMPORTANT
## - comment out or remove SOURCE() function




## STEP-0: make sure that no Oxygen documatation is done. If there is, remove it. Otherwise, you get the ff error:
# > roxygenise(package.dir = "./")
# Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
# Warning: aCRFExtractor_mainFn.R:10: @example /Users/workuhm/Desktop/Data Science/awash_analytics/proj-mini-parse-aCRF-page/prod/aCRFExtractor/run_aCRFExtractor() doesn't exist
# Warning: get_linkPages_fn.R:11: @example /Users/workuhm/Desktop/Data Science/awash_analytics/proj-mini-parse-aCRF-page/prod/aCRFExtractor/linkPages <- get_linkPages(dsin = crf_preprocess, dset_defOrigin = defineOrigin_variableTab3) doesn't exist

# STEP-1: devtools::install_github("hadley/devtools")
library(devtools)
library(roxygen2)
# library(testthat)

## STEP-2, option-1: modify NAMESPACE, use func::export. Include R functions, not the R files.
## -- DONOT use this part
# exportPattern("^[[:alpha:]]+")
# export(run_aCRFExtractor)
# export(get_finalaCRFpages)
# export(get_linkPages)
# export(get_pgsSpecialVars)
# export(get_sdtmVars_pgNbr)
# export(preprocess_crf)

## STEP-2, option-2: NAMESPACE, do not perform this part. Otherwise, the func::eoxygenise overwrites NAMESPACE file!!!
# > roxygenise(package.dir = "./")
# Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
# Deleting run_aCRFExtractor.Rd
## -- Thus, to resolve the issue perform the ff task
## -- 1. Delete NAMESPACE which was created authomatically. Otherwise, you get the ff error:
## -- 2. Run the code below
## --- source: https://stackoverflow.com/questions/29135971/namespace-not-generated-by-roxygen2-skipped-confusion-with-hadley-book
# devtools::document()

## STEP-3: once you creted the package via Rstudio project setup
## -- 1. modify DESCRIPTION file
##    1.1. This the way to setup dependence of my pkg with others
##         Remotes: github::hadley/devtools, github::tidyverse/tidyr, github::tidyverse/readr
##         Dependence: R (>= 3.3.3), tidyr, pdftools, stringr, xlsx, sqldf
##         Imports: devtools, tidyr, pdftools, stringr, xlsx, sqldf, readr

## -- 2. To verify DESCRIPTION file, run <load_all()>
## -- you should see a message <Loading aCRFMinner>


## STEP-4: add description file
load_all()             ## not working, instead create pkg via Rstudio project
# load_all("./")


## STEP-5: documentation, do not perform this part. Otherwise, the func::eoxygenise overwrites NAMESPACE file
## -- The ff warning messgae is expected and it's fine. SOURCE: https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html
## -- Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
roxygen2::roxygenise(package.dir = "./")

## ROxygen2 tips for documentation
## Examples keyword, new line generation
## -- #' @examples
#' require(aCRFExtractor)
#' run_aCRFExtractor()


## STEP-6: Proceed with building the pkg
## -- Click 'Install and Restart' 

## STEP-7: Check package using pgk::devtools. 
## Note that this step doesn't work in RStudio interface
devtools::check()

## STEP-8: Build binary package
## Go to "More ->Build Binary package"